global:
  scrape_interval: 15s 

scrape_configs:

 
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']

 
  - job_name: 'flask-app'
    static_configs:
      - targets: ['flask-app:8080']  

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  
